#
# Pipeline Daemon Docker Compose file for Open DevOps Pipeline
#
# VERSION : 1.0
#
version: '2'

services:
  jenkins:
    image: devopsopen/pipeline-daemon
    ports:
      - "8700:8080"
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - DOCKER_HOST=${DOCKER_HOST}
    restart: never
    volumes:
      - /opt/opendevops/bin:/go/bin
